sequenceDiagram
	actor EU as End User
	participant FE as Application frontend
	participant BE as Application backend
	participant CP as Vonage API gateway
	participant OP as Mobile Operator

	activate EU
		EU->>FE: Submits sign-up form
		activate FE
			FE->>BE: POST /authorize?request_id
			activate BE
				BE->>CP: POST /network-enablement
				activate CP
					CP-->>BE: 200 auth_url
				deactivate CP
				BE->>FE: 200 auth_url
			deactivate BE
			FE->>CP: GET /auth_url?request_id
			activate CP
				CP-->>FE: 302 (redirect) Location: /authorize
			deactivate CP
			FE-->>OP: GET /authorize
			activate OP
				OP-->>FE: 302 (redirect) Location: /callback?operator_code
			deactivate OP
			FE-->>CP: GET /callback?operator_code
			activate CP
				CP->>OP: POST /token?operator_code
				activate OP
					OP-->>CP: 200 operator_access_token
				deactivate OP
				CP->>CP: Generate code to resolve operator_access_token later
				CP-->>FE: 302 (redirect) Location: /callback?code&request_id
			deactivate CP
			FE-->>BE: GET /callback?code&request_id
			activate BE
				BE->>CP: POST /token?code
				activate CP
					CP->>CP: Resolve operator_access_token and embed it along with routing info into a access_token
					CP-->>BE: 200 access_token
				deactivate CP
				BE->>BE: Keeps access_token for request_id
				BE-->>FE: 200
			deactivate BE
			FE-->>BE: POST /signup?request_id
			activate BE
				BE->>BE: Takes access_token for request_id
				BE->>CP: /number-verification?access_token
				activate CP
					CP->>CP: Unembed operator routing information and operator_access_token
					CP->>OP: /number-verification?operator_access_token
					activate OP
						OP-->>CP: 200 true/false
					deactivate OP
					CP-->>BE: 200 true/false
			alt If number can be verified
					BE->>FE: 201
					FE-->>EU: Displays success message
			else If number cannot be verified
					BE->>CP: POST /send-2fa-challenge
					BE->>FE: 202
					FE-->>EU: Displays 2FA pending message
					CP-->>EU: (SMS/Email) 2FA challenge sent
				deactivate CP
				EU->>FE: Submits 2FA
				FE->>BE: POST /signup?request_id&2FA
				BE-->>FE: 200
				FE-->>EU: Displays success message
			deactivate BE
			end
		deactivate FE
	deactivate EU